# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.Agent
PackageVersion: v1.148.0
InstallerType: portable
Commands:
- docker-agent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.148.0/docker-agent-windows-amd64.exe
  InstallerSha256: 5B269600487EF6A01826DD4CB8AF42DF85D2A4F0ADDC889D2572E55AFDA347BE
- Architecture: arm64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.148.0/docker-agent-windows-arm64.exe
  InstallerSha256: E14D82ABFEFB55865EEAD95FD337558E3FCE3600463F09AB03E8E99BD4C60602
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
