# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.Agent
PackageVersion: v1.149.0
InstallerType: portable
Commands:
- docker-agent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.149.0/docker-agent-windows-amd64.exe
  InstallerSha256: B9BCFBE853138B6E191311CCFA01B6AB7DB24B45BC40A6DBC8708BCFACEDCDF8
- Architecture: arm64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.149.0/docker-agent-windows-arm64.exe
  InstallerSha256: 1290DF4350A78099770231D196577A1594003D399446B86A39AD380A17058222
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
