# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.Agent
PackageVersion: v1.147.0
InstallerType: portable
Commands:
- docker-agent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.147.0/docker-agent-windows-amd64.exe
  InstallerSha256: 98EB6F73BE4573868BFE0C83742E4AF242D69B95833EDD142568115B3F47D6D5
- Architecture: arm64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.147.0/docker-agent-windows-arm64.exe
  InstallerSha256: 23E65F9CC927C600B63821AA4A141DF5E98F7BABCE65A3C255F12B628D6097EC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
